# Generated by Django 5.0.7 on 2024-10-12 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudnation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('United States - Michigan', 'United States - Michigan'), ('India - Mumbai', 'India - Mumbai')], max_length=255)),
                ('framework', models.CharField(choices=[('Vue.js', 'Vue.js'), ('React', 'React'), ('Express.js', 'Express.js'), ('Ruby on Rails', 'Ruby on Rails')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='appplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Starter, 10 GB, 512 MB, 2, $0.0278, $20', 'Starter, 10 GB, 512 MB, 2, $0.0278, $20'), ('Basic, 10 GB, 1 GB, 2, $0.0417, $30', 'Basic, 10 GB, 1 GB, 2, $0.0417, $30'), ('Standard, 10 GB, 2 GB, 2, $0.0625, $45', 'Standard, 10 GB, 2 GB, 2, $0.0625, $45'), ('Performance, 10 GB, 4 GB, 2, $0.0972, $70', 'Performance, 10 GB, 4 GB, 2, $0.0972, $70'), ('Pro, 10 GB,8 GB, 2, $0.1597, $115', 'Pro, 10 GB,8 GB, 2, $0.1597, $115')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='databasedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('Postgresql', 'Postgresql'), ('Mysql', 'Mysql')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dbplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Starter, 10 GB, 512 MB, 2, $0.0278, $20', 'Starter, 10 GB, 512 MB, 2, $0.0278, $20'), ('Basic, 10 GB, 1 GB, 2, $0.0417, $30', 'Basic, 10 GB, 1 GB, 2, $0.0417, $30'), ('Standard, 10 GB, 2 GB, 2, $0.0625, $45', 'Standard, 10 GB, 2 GB, 2, $0.0625, $45'), ('Performance, 10 GB, 4 GB, 2, $0.0972, $70', 'Performance, 10 GB, 4 GB, 2, $0.0972, $70'), ('Pro, 10 GB,8 GB, 2, $0.1597, $115', 'Pro, 10 GB,8 GB, 2, $0.1597, $115')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='envvariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='githubdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
